Update README.md with contributor's name
socratesjnr/asuu-strike-project pull request #7
Opened 2023-05-16 08:31 UTC by fkajose

I included "Oluwaseyi Adaramola" in the authors list

2023-05-16 10:22 UTC, socratesjnr requested changes
The second one, VIZ_STYLEGUIDE.md is not displaying properly, kindly check, I do not know I that will display as we want it to in the Read Me.

2023-05-16 11:01 UTC, fkajose commented
There are no issues. It's not displaying properly because I have attached no images to it. I'll attach when the visualization team has generated one.

2023-05-17 20:59 UTC, socratesjnr commented
Okay cool

2023-05-17 21:00 UTC, socratesjnr approved these changes

2023-05-17 21:09 UTC, merged